# Generated by Django 4.2.6 on 2024-06-23 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import platform_main.models.campaign
import platform_main.models.user
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_stopped', models.BooleanField(default=False)),
                ('allow_zero_balance', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, utils.models.TimestampMixin),
            managers=[
                ('objects', platform_main.models.user.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('0', 'No email'), ('1', 'Email')])),
                ('format', models.CharField(choices=[('pop', 'Pop'), ('banner', 'Banner'), ('redirect', 'Redirect')])),
                ('link', models.CharField(max_length=250)),
                ('platform', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile')])),
                ('os', platform_main.models.campaign.ChoiceArrayField(base_field=models.CharField(choices=[('windows', 'Windows'), ('linux', 'Linux'), ('macos', 'MacOS'), ('android', 'Android'), ('ios', 'IOS')], max_length=20), size=None)),
                ('geo', models.CharField(choices=[('uk', 'United Kingdom'), ('us', 'United States')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('clicks_per_day', models.IntegerField()),
                ('current_status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped')], default='stopped')),
                ('next_status', models.CharField(choices=[('stop_requested', 'Stop requested'), ('run_requested', 'Run requested')], null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, utils.models.TimestampMixin),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('system_id', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, utils.models.TimestampMixin),
        ),
        migrations.CreateModel(
            name='SourcePrice',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('0', 'No email'), ('1', 'Email')])),
                ('format', models.CharField(choices=[('pop', 'Pop'), ('banner', 'Banner'), ('redirect', 'Redirect')])),
                ('platform', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile')])),
                ('geo', models.CharField(choices=[('uk', 'United Kingdom'), ('us', 'United States')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_main.source')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, utils.models.TimestampMixin),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('type', models.CharField(choices=[('bank', 'Bank'), ('capitalist', 'Capitalist'), ('usdt', 'USDT')])),
                ('paid', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField()),
                ('clicks', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='platform_main.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='platform_main.source'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to=settings.AUTH_USER_MODEL),
        ),
    ]
