# Generated by Django 4.2.6 on 2024-07-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='geo',
            field=models.CharField(choices=[('gb', 'United Kingdom'), ('us', 'United States'), ('ar', 'Argentina'), ('au', 'Australia'), ('at', 'Austria'), ('be', 'Belgium'), ('br', 'Brazil'), ('bg', 'Bulgaria'), ('ca', 'Canada'), ('cl', 'Chile'), ('cn', 'China'), ('co', 'Colombia'), ('hr', 'Croatia'), ('cz', 'Czech Republic'), ('dk', 'Denmark'), ('ee', 'Estonia'), ('fi', 'Finland'), ('fr', 'France'), ('de', 'Germany'), ('gr', 'Greece'), ('hu', 'Hungary'), ('in', 'India'), ('ie', 'Ireland'), ('il', 'Israel'), ('it', 'Italy'), ('jp', 'Japan'), ('lv', 'Latvia'), ('lt', 'Lithuania'), ('lu', 'Luxembourg'), ('my', 'Malaysia'), ('mx', 'Mexico'), ('nl', 'Netherlands'), ('nz', 'New Zealand'), ('ng', 'Nigeria'), ('no', 'Norway'), ('pl', 'Poland'), ('pt', 'Portugal'), ('ro', 'Romania'), ('ru', 'Russia'), ('sa', 'Saudi Arabia'), ('sg', 'Singapore'), ('sk', 'Slovakia'), ('si', 'Slovenia'), ('za', 'South Africa'), ('es', 'Spain'), ('se', 'Sweden'), ('ch', 'Switzerland'), ('th', 'Thailand'), ('tr', 'Turkey')]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sourceprice',
            name='geo',
            field=models.CharField(choices=[('gb', 'United Kingdom'), ('us', 'United States'), ('ar', 'Argentina'), ('au', 'Australia'), ('at', 'Austria'), ('be', 'Belgium'), ('br', 'Brazil'), ('bg', 'Bulgaria'), ('ca', 'Canada'), ('cl', 'Chile'), ('cn', 'China'), ('co', 'Colombia'), ('hr', 'Croatia'), ('cz', 'Czech Republic'), ('dk', 'Denmark'), ('ee', 'Estonia'), ('fi', 'Finland'), ('fr', 'France'), ('de', 'Germany'), ('gr', 'Greece'), ('hu', 'Hungary'), ('in', 'India'), ('ie', 'Ireland'), ('il', 'Israel'), ('it', 'Italy'), ('jp', 'Japan'), ('lv', 'Latvia'), ('lt', 'Lithuania'), ('lu', 'Luxembourg'), ('my', 'Malaysia'), ('mx', 'Mexico'), ('nl', 'Netherlands'), ('nz', 'New Zealand'), ('ng', 'Nigeria'), ('no', 'Norway'), ('pl', 'Poland'), ('pt', 'Portugal'), ('ro', 'Romania'), ('ru', 'Russia'), ('sa', 'Saudi Arabia'), ('sg', 'Singapore'), ('sk', 'Slovakia'), ('si', 'Slovenia'), ('za', 'South Africa'), ('es', 'Spain'), ('se', 'Sweden'), ('ch', 'Switzerland'), ('th', 'Thailand'), ('tr', 'Turkey')]),
        ),
        migrations.AlterField(
            model_name='sourceprice',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
